# Generated by Django 4.2.15 on 2024-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
